services:
    # Aplicação Laravel
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: sergio
                uid: 1002
        container_name: portfolio-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - portfolio-network

    # Nginx Service
    nginx:
        image: nginx:alpine
        container_name: portfolio-nginx
        restart: unless-stopped
        ports:
            - "8003:80"
            - "5173:5173"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
        networks:
            - portfolio-network
        depends_on:
            - app

    # MySQL Service
    db:
        image: mysql:8.0
        container_name: portfolio-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3309:3306"
        networks:
            - portfolio-network

    
networks:
    portfolio-network:
        driver: bridge

volumes:
    dbdata:
