services:
  # Aplicação Laravel
  app:
    image: sergio72/portifolio-app:latest  # Substitua "seu_usuario_docker" pelo seu username real do Docker Hub
    container_name: portifolio-app
    restart: always
    working_dir: /var/www
    volumes:
      - app-storage:/var/www/storage
    networks:
      - portifolio-network
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=${APP_URL:-https://projetosdev.com}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: portifolio-nginx
    restart: always
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - app-storage:/var/www/storage
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
      - /etc/ssl/certs/seudominio.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/ssl/certs/seudominio.com/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    networks:
      - portifolio-network
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: portifolio-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - portifolio-network

networks:
  portifolio-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  app-storage:
    driver: local